### PR TITLE
improve CLI usability

### PR DESCRIPTION
**Pull request by deepthawtz**
* help output for each command
* cleaner way of handling required vs. optional arguments
* display meaningful error when commands used incorrectly

### CODE REVIEW

**Comment by deepthawtz** [comment]
@unwriter any interest in this? no worries if you aren't taking contributions

**Comment by unwriter** [comment]
@deepthawtz sorry for the delay, yes I am interested, but just didn't have time to look thoroughly into it because the changes are a bit overwhelming.

I understand it's basically the same code but with commander, but the thing that makes it hard to review is because the diff is not helping (basically the diff shows as if the entire file contents have changed).

I do want to integrate this somehow but will need to take some time, since I don't want to just hastily merge and break it for everyone who's using the tool. 

p.s.

One thing that might help in moving forward more quickly is if you could break this down into multiple PRs (actually, it could even be just a single PR broken down to multiple commits so each step can be checked easily) so it's easier to tell what exactly has changed for each step. Then I could merge one by one, and I have no problem accepting PRs as long as the changes are obvious and I can tell the difference easily. (As you can see [here](https://github.com/interplanaria/bottle/pulls?q=is%3Apr+is%3Aclosed) I am very open with contributions)

**Comment by deepthawtz** [comment]
I can break this PR up into smaller atomic commits so it this is easier to review

**Comment by unwriter** [comment]
@deepthawtz that would be perfect, thank you.

**Comment by deepthawtz** [comment]
@unwriter I'm in process of separating my commits and I only just now noticed you had two separate `if (cmd === 'ls')` sections that do different things (first one wins, so second one can never be called )

https://github.com/interplanaria/pc/blob/master/index.js#L378
vs.
https://github.com/interplanaria/pc/blob/master/index.js#L848

Do you want to rename one of those commands or combine them in some way (distinguished between each other perhaps by an argument) so that both commands can be used?

**Comment by unwriter** [comment]
@deepthawtz why don't we just get rid of the unused one (https://github.com/interplanaria/pc/blob/master/index.js#L848) for now? I think it can be revisited later.

**Comment by deepthawtz** [comment]
@unwriter OK, finished extracting all the commands.

**Comment by unwriter** [comment]
@deepthawtz Thanks, this is a huge progress! 

Found a small typo but just fixed it myself https://github.com/interplanaria/pc/commit/268d6ab888368a2403267f270908669bbea0fc3a :)

But otherwise, have been test driving it for a bit and mostly seems to be working well. Thanks!

**Pull request merged**
